name: MLOps Pipeline Hardening

on: [push, pull_request]

jobs:
  scan-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install mlsecure
      run: pip install -e .

    - name: Run secret scan
      run: mlsecure scan-secrets --path .
